add comments to ci workflow reflecting branch protection rules (#141)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -48,6 +48,20 @@ jobs:
       - name: Run tests in "${{ matrix.BUILD_TARGET }}" mode
         run: cargo test --profile ${{ matrix.BUILD_TARGET }} --all-features
 
+  # WARNING: do not change this job name. It is a required status check for PRs to `main`.
+  build-result:
+    needs: build
+    runs-on: ubuntu-latest
+    if: ${{ !cancelled() }}
+    steps:
+      - name: Verify all build steps passed
+        run: |
+          if [[ "${{ needs.build.result }}" != "success" ]]; then
+            echo "build failed or was cancelled"
+            exit 1
+          fi
+
+  # WARNING: do not change this job name. It is a required status check for PRs to `main`.
   asan:
     runs-on: ubuntu-latest
     steps:
@@ -100,6 +114,7 @@ jobs:
       - name: Run tests
         run: cargo build --target=$DEFAULT_RUST_TARGET --profile=dev --all-features
 
+  # WARNING: do not change this job name. It is a required status check for PRs to `main`.
   clippy:
     runs-on: ubuntu-latest
     steps:
